version: 2.1 # 2.1 config required to use orbs

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4
  aws-ecr: circleci/aws-ecr@8.1.2 # use the AWS ECR orb
  aws-ecs: circleci/aws-ecs@3.2.0 # use the AWS ECS orb
  aws-cli: circleci/aws-cli@3.1.1 # use the AWS CLI orb

jobs:
  app-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
  app-build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Run build
  docker-build:
    executor: docker/docker
    steps:
      - checkout
      - run:
          command: docker compose build
          name: Docker compose build
  # docker-push:
  #     executor: node/default
  #     steps:
  #         - checkout
  #         - node/install-packages:
  #             pkg-manager: npm
  #         - run:
  #             command: npm run build
  #             name: Run build
  # verify-deployment:
  #     executor: aws-cli/default
  #     steps:
  #         - aws-cli/install
  #         - aws-cli/setup:
  #               aws-access-key-id: AWS_SECRET_ACCESS_KEY
  #               aws-region: AWS_DEFAULT_REGION
  #               aws-secret-access-key: AWS_DEFAULT_REGION
  #         - run:
  #               name: Get last task definition
  #               command: >
  #                   TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
  #                       --task-definition ${MY_APP_PREFIX}-service \
  #                       --output text \
  #                       --query 'taskDefinition.taskDefinitionArn')
  #                   echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
  #                   "$BASH_ENV"
  #         - aws-ecs/verify-revision-is-deployed:
  #               family: "${MY_APP_PREFIX}-service"
  #               cluster: "${MY_APP_PREFIX}-cluster"
  #               task-definition-arn: "${TASK_DEFINITION_ARN}"

workflows:
  build-and-deploy:
    jobs:
      - app-test
      - app-build
      - docker-build
      # - docker-push
      # - aws-ecr/build-and-push-image:
      #       repo: "${MY_APP_PREFIX}"
      #       tag: "${CIRCLE_SHA1}"
      # - aws-ecs/deploy-service-update:
      #       requires:
      #           - aws-ecr/build-and-push-image
      #       family: "${MY_APP_PREFIX}-service"
      #       cluster: "${MY_APP_PREFIX}-cluster"
      #       container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"
      # - verify-deployment:
      #       requires:
      #           - aws-ecs/deploy-service-update
